# Generated by Django 3.0.7 on 2020-09-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0003_auto_20200925_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('online', 'Электронно')], default='online', max_length=6, verbose_name='Способ оплаты'),
        ),
    ]
