# Generated by Django 3.0.7 on 2020-09-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0034_auto_20200920_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Обработанный'), ('unprocessed', 'Необработанный')], default='unprocessed', max_length=11),
        ),
    ]
